<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <PlatformToolset Condition="'$(RfiToolset)' != ''">$(RfiToolset)</PlatformToolset>
    <PlatformToolset Condition="'$(RfiToolset)' == ''">v145</PlatformToolset>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <LanguageStandard>stdcpp20</LanguageStandard>
      <SDLCheck>true</SDLCheck>
      <ControlFlowGuard>Guard</ControlFlowGuard>
      <BufferSecurityCheck>true</BufferSecurityCheck>
      <WarningLevel>Level3</WarningLevel>
      <PreprocessorDefinitions>UNICODE;_UNICODE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <AdditionalOptions>/utf-8 %(AdditionalOptions)</AdditionalOptions>
      <RuntimeLibrary Condition="'$(Configuration)'=='Debug'">MultiThreadedDebugDLL</RuntimeLibrary>
      <RuntimeLibrary Condition="'$(Configuration)'!='Debug'">MultiThreadedDLL</RuntimeLibrary>
      <SpectreMitigation>false</SpectreMitigation>
    </ClCompile>
    <Link>
      <AdditionalOptions>/guard:cf %(AdditionalOptions)</AdditionalOptions>
    </Link>
  </ItemDefinitionGroup>
</Project>
